# -*- coding: utf-8 -*-
"""workshop ckass 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-MX1AHeertBCyShqTNgBLXubRzJhr5kU
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd 
import plotly.express as pr
import plotly.graph_objects as go

#read the data set
df = pd.read_csv('/content/project_dataset.csv')

df

df1 = df.copy()
df1

df1.head()

df1.tail()

df1.head(60)

df1.shape

df1.info

df1.dtypes

df1.columns

df1.describe()

df1.duplicated()

df1.isna()

df1.isna().sum()

df1.isna().sum()/df1.shape[0]

df1.dropna(axis=1)

df

df1.dropna(axis=1,inplace = True)

df1

df1.dtypes

df1.shape

data = df1.sample(n = 500, random_state = 42)

data

data.head()

data.tail

data = data.drop(['Unnamed: 0'],axis = 1)

data.shape

data

fig = go.Figure(data = go.Scatter(x=df['Distance'],y = df['DepTime'],mode='markers', marker=dict(color='red')))
fig.update_layout(title = 'Scatter Plot for Distance vs Departure time', xaxis_title = 'Distance Time',yaxis_title ='Departure Time')
fig.show()

line_data = df.groupby('Month')['ArrDelay'].mean().reset_index()
line_data

fig = go.Figure(data = go.Scatter(x=line_data['Month'],y = line_data['ArrDelay'],mode='lines', marker=dict(color='green')))
fig.update_layout(title = 'Monthly average delay plot for an year', xaxis_title = 'Months',yaxis_title ='Delay of flights (in minutes)')
fig.show()

bar_data = df.groupby('DestState')['Flights'].sum().reset_index()
bar_data

fig = pr.bar(bar_data,x='DestState',y='Flights', title = 'Total number of flights from each destination states')
fig.show()

bub_data = df.groupby('Reporting_Airline')['Flights'].sum().reset_index()
bub_data

fig = pr.scatter(bub_data,x='Reporting_Airline',y='Flights', title = 'Total number of flights per reporting airlines',size = 'Flights',hover_name='Reporting_Airline',size_max=60)
fig.show()

